# Generated by Django 5.0.4 on 2024-05-01 04:02

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingPoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='studentactivity',
            name='student',
        ),
        migrations.AddField(
            model_name='activity',
            name='student',
            field=models.ManyToManyField(related_name='StudentActivity', to='TrainingPoint.student'),
        ),
        migrations.AlterField(
            model_name='missingpointreport',
            name='proof',
            field=models.FileField(upload_to='missing_point_proofs/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='ban_tin/%Y/%m'),
        ),
        migrations.CreateModel(
            name='StudentAffairsOfficer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPoint.department')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('TrainingPoint.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingPoint.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'news')},
            },
        ),
    ]
