# Generated by Django 5.0.4 on 2024-05-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingPoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactivity',
            name='achievement',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news/%Y/%m'),
        ),
    ]
